version: "3"
services:
    server:
        build:
            context: ./site
            dockerfile: Dockerfile
        volumes:
            - ./site/src:/home/node/app
        ports:
            - "3000:8000"
