version: "3"
services:
    server:
        build:
            context: ./website
            dockerfile: Dockerfile
        volumes:
            - ./website/src:/home/node/app
        ports:
            - "3000:8000"
